### ISSUE TITLE
Allow multi-line commands

### ISSUE THREAD

**Issue by SorraTheOrc** [Azure/simdem#83]
Currently multi-line commands are not supported, for example:

```
az managed app definition create \
    -- name $MANAGED_APP_NAME
```

Results in:

```
az managedapp definition create \
Traceback (most recent call last):
  File "/usr/local/bin/simdem", line 145, in <module>
    main()
  File "/usr/local/bin/simdem", line 143, in main
    demo.run(cmd)
  File "/usr/local/bin/simdem-dev/demo.py", line 212, in run
    failed_tests, passed_tests = self.execute(classified_lines)
  File "/usr/local/bin/simdem-dev/demo.py", line 589, in execute
    actual_results = self.ui.simulate_command()
  File "/usr/local/bin/simdem-dev/cli.py", line 206, in simulate_command
    output = self.run_command()
  File "/usr/local/bin/simdem-dev/cli.py", line 277, in run_command
    response = self.get_shell().run_command(command)
  File "/usr/lib/python3/dist-packages/pexpect/replwrap.py", line 100, in run_command
    + command)
ValueError: Continuation prompt found - input was incomplete:
az managedapp definition create \
```

**Comment by lastcoolnameleft** [comment]
Did you ever have any thoughts on how to accomplish this?  

I'm hitting a similar roadblock when trying to make something like:
```
until [ $FOO ]
do
    FOO=$(polling_command.sh)
    sleep 5
done
```

**Comment by SorraTheOrc** [comment]
These are two different cases. Mine was a single command over multiple lines using the '\' continuation character. This is easy, simply look for the continuation character at EOL.

Yours is more complex and would require parsing of the command.

**Comment by lastcoolnameleft** [comment]
Ugg...you're right.  The issue with mine is that the prompt changes if there's an unmatched until and which breaks the pexpect prompt.  Back to the drawing board.

**Comment by jasonmesser7** [comment]
Flagging this issue again. I was about to create a new issue and saw this. Most Microsoft docs are written with multi line commands, and so in order to execute Microsoft docs we need to support multi line commands.

**Comment by jasonmesser7** [comment]
Marking as a P-High as this will enable us to take a lot of existing docs in Azure Open Source Labs and execute them
